### PR TITLE
Add sentiment analysis notebook

### PR DESCRIPTION
**Pull request by cgraywang**
Add sentiment analysis notebook using pretrained embedding and biLSTM.

### CODE REVIEW

**Comment by astonzhang** [comment]
Let's just improve the style per our offline discussions. Thanks for the contributions!

**Comment by szha** [comment]
This example could have been a lot simpler with the nlp package. I understand from offline discussion that you want to avoid using experimental features. If that's the case, all references to mxnet.contrib (including contrib.text) should be removed. If not, then it's much simpler to use the toolkit as was done in https://gluon-nlp.mxnet.io/examples/sentiment_analysis/sentiment_analysis.html.

**Comment by astonzhang** [comment]
We'll still use contrib.text by assuming that it is stable.

**Comment by cgraywang** [comment]
I think it is fine to use the contrib.text version. The example is to illustrate the easy usage of gluon alone (without gluonnlp) to build sentiment analysis model, which is different from the purpose of sentiment analysis example in gluonnlp.

**Comment by astonzhang** [comment]
In comparison with implementing pre-trained embedding from scratch, I think using existing API is more reasonable. We might use gluonnlp but its chance of change is much higher than that of contrib.text.

**Comment by cgraywang** [comment]
@szha It really depends. 1) any version can be unstable. If the Gluonnlp is now in Gluon. It will be more stable. But now Gluonnlp is separate. So you see if it is finally in Gluon, we will need to change a lot. 2) the tutorial should be consistent. In the natural language processing session and the online video, we have already used the text api in contrib, it will be strange to the users that they have the book and find the api is different from what they have learned. 3) now the example is just using basics (vocab and embedding) of the text API, I believe this part can be stable. Why not we just use this, and not take the risk to change.

**Comment by szha** [comment]
@cgraywang, given that: 
> 1) any version can be unstable. If the Gluonnlp is now in Gluon. It will be more stable.
The stability of a package depends only on how the version is managed, not on where it resides. Also, a released a version is a snapshot that no longer will change so the question of stability doesn't apply to a specific version.

> 2) the tutorial should be consistent.
Indeed. My impression is that the contrib.text API for MOOC was rushed, and the merge of it was a compromise under circumstances. Will elaborate more below.

> it will be strange to the users ... find the api is different from what they have learned
That's my concern exactly.  If we are making the same material into a book, I don't think including contrib API is better than including gluonnlp, especially if stability is the concern.
contrib.text was merged as a compromise for the need of weekly MOOC under tight deadline. contrib.text was expected to change, and [it even says so in the tutorial](https://github.com/mli/gluon-tutorials-zh/blob/master/chapter_natural-language-processing/pretrained-embedding.md#%E5%BA%94%E7%94%A8%E8%AF%8D%E5%90%91%E9%87%8F%E6%B1%82%E8%BF%91%E4%BC%BC%E8%AF%8D%E5%92%8C%E7%B1%BB%E6%AF%94%E8%AF%8D). Now that the maintained version resides in gluonnlp, naturally the references to contrib.text should be revisited.

> Why not we just use this, and not take the risk to change.
Because if we do so, we are teaching people to use an API that we don't have intention of maintaining.

**Comment by cgraywang** [comment]
@szha 

>> >> 1. any version can be unstable. If the Gluonnlp is now in Gluon. It will be more stable.

>> The stability of a package depends only on how the version is managed, not on where it resides. Also, a released a version is a snapshot that no longer will change so the question of stability doesn't apply to a specific version.

Yes, that is exactly what I mean. We should not write everything from scratch in this notebook, 
 this will drift the attention from the sentiment analysis itself. I think we both agree on this @astonzhang . Then we should use an more stable API in the tutorial. Are we going to maintain Gluonnlp for a long term run? Or it will eventually go into Gluon. I remember our plan is to merge into Gluon not maintain a separate Gluonnlp. In this case, contrib.text will be more stable compare to Gluonnlp for now, if we are not going to delete contrib.text.

For 
>> >> the tutorial should be consistent.

>> >> it will be strange to the users ... find the api is different from what they have learned

>> >> Why not we just use this, and not take the risk to change.

I think we have agreed on the consistency and minimization of the risk of chance of changing API.

**Comment by szha** [comment]
sorry I can't make sense of the above.

**Comment by szha** [comment]
Why would there be risk of changing API if this package depend on gluonnlp==0.2.0?

**Comment by szha** [comment]
reading a couple of more times, it seems that the point that couldn't be agreed on is which API is more stable.

GluonNLP has the more stable version of the vocab and embedding API. Whether it will go into mxnet repo or not is hardly relevant.

contrib.text is in contrib package, which hosts only experimental packages and will no longer be maintained. We will likely clear out some old contrib package in the next major version of mxnet.

**Comment by astonzhang** [comment]
@szha 

In the long run, MXNet/Gluon is also unstable, which will cause some code in the book to break. For instance, we fixed some code in the book after MXNet is updated from 20180403 to 20180423. Hence, we will clarify in the book that code may change, including any possible future changes to mxnet.contrib. Thus, it is fine to use mxnet.contrib, even if it may change in the future.

As we discussed, gluonnlp will be merged into gluon. In that case, I don't think we will maintain both gluon.nlp and gluonnlp. Likely, we deprecate gluonnlp then it may be confusing to mention gluonnlp in the book.

**Comment by szha** [comment]
gluonnlp is unlikely to be merged back within the year, and in between there will be many releases in mxnet, which means by the time gluonnlp becomes gluon.nlp. If you have the flexibility of changing the code to accommodate when contrib.text is deleted, I don’t see why the same flexibility couldn’t apply to gluonnlp.

Most of the dataset loading and parsing in this PR becomes unnecessary by integrating gluonnlp, because it has already been supported. If you insist on having users to read the boiler plates, feel free to proceed.

**Comment by astonzhang** [comment]
I agree that using gluonnlp saves code. However,

1. If we introduce gluonnlp in the book, users may "pip install gluonnlp", especially if they directly jump into this chapter. However, it is hard to guarantee that gluonnlp is always available in the future.
2. Since we are actively maintaining gluonnlp not contrib.text, the chance of breaking code is higher if we use gluonnlp in the book.

Besides, it is fine to use contrib package. For instance, the book "Hands on ML with Scikit learn and TF" uses 
```
from tensorflow.contrib.layers import fully_connected
```

Thank you for raising the concerns. By considering all the positive and negative factors, I still prefer using contrib at the moment.

**Comment by szha** [comment]
1. the pip package of gluonnlp==0.2.0 will remain available for as long as pip exists. there's no need to delete the released packages even if gluonnlp eventually merges into mx.gluon.
2. do you really mean it that unmaintained code is more stable? we actively maintain mxnet and yet we don't dismiss the usage of symbol or ndarray besides gluon, do we?

I don't think any of the "negative factors" apply.

**Comment by astonzhang** [comment]
1. Why should we ask users to use gluonnlp==0.2.0 if in the end users cannot do "pip install gluonnlp"?  
2. We expect more code changes in gluonnlp than contrib.text, do we? I think that may increase chance of code break if we use gluonnlp.

**Pull request merged**
