### PR TITLE
内容修正

### PR DESCRIPTION
**Pull request by wangx404**
对图像增广和微调两节中的部分语句进行了修正。

### CODE REVIEW

**Comment by wangx404** [comment]
对图像增广和微调两节中的部分语句进行了修正。

**Comment by astonzhang** [comment]
Thanks. Can you move gan parts into contrib dir? We do not plan to include gan in the current version (maybe include in the future).

**Comment by wangx404** [comment]
OK, I have deleted this part. Now it could be merged.

**Comment by astonzhang** [comment]
Very good edits. Please proceed with the rest of this chapter :)

**Comment by wangx404** [comment]
I will edit the rest of this chapter if I have free time this weekend.

**Pull request merged**
